insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('アイスランド','Iceland','352','ISL','IS','北ヨーロッパ','ISO 3166-2:IS');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('アイルランド','Ireland','372','IRL','IE','西ヨーロッパ','ISO 3166-2:IE');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('アゼルバイジャン','Azerbaijan','031','AZE','AZ','東ヨーロッパ','ISO 3166-2:AZ');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('アフガニスタン','Afghanistan','004','AFG','AF','中東','ISO 3166-2:AF');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('アメリカ合衆国','United States','840','USA','US','北アメリカ','ISO 3166-2:US');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('アメリカ領ヴァージン諸島','Virgin Islands U.S.','850','VIR','VI','中央アメリカ','ISO 3166-2:VI');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('アメリカ領サモア','American Samoa','016','ASM','AS','オセアニア','ISO 3166-2:AS');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('アラブ首長国連邦','United Arab Emirates','784','ARE','AE','中東','ISO 3166-2:AE');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('アルジェリア','Algeria','012','DZA','DZ','北アフリカ','ISO 3166-2:DZ');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('アルゼンチン','Argentina','032','ARG','AR','南アメリカ','ISO 3166-2:AR');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('アルバ','Aruba','533','ABW','AW','中央アメリカ','ISO 3166-2:AW');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('アルバニア','Albania','008','ALB','AL','東ヨーロッパ','ISO 3166-2:AL');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('アルメニア','Armenia','051','ARM','AM','東ヨーロッパ','ISO 3166-2:AM');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('アンギラ','Anguilla','660','AIA','AI','中央アメリカ','ISO 3166-2:AI');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('アンゴラ','Angola','024','AGO','AO','南アフリカ','ISO 3166-2:AO');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('アンティグア・バーブーダ','Antigua and Barbuda','028','ATG','AG','中央アメリカ','ISO 3166-2:AG');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('アンドラ','Andorra','020','AND','AD','西ヨーロッパ','ISO 3166-2:AD');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('イエメン','Yemen','887','YEM','YE','中東','ISO 3166-2:YE');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('イギリス','United Kingdom','826','GBR','GB','西ヨーロッパ','ISO 3166-2:GB');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('イギリス領インド洋地域','British Indian Ocean Territory','086','IOT','IO','インド洋地域','ISO 3166-2:IO');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('イギリス領ヴァージン諸島','Virgin Islands British','092','VGB','VG','中央アメリカ','ISO 3166-2:VG');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('イスラエル','Israel','376','ISR','IL','中東','ISO 3166-2:IL');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('イタリア','Italy','380','ITA','IT','西ヨーロッパ','ISO 3166-2:IT');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('イラク','Iraq','368','IRQ','IQ','中東','ISO 3166-2:IQ');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('イラン・イスラム共和国','Iran Islamic Republic of','364','IRN','IR','中東','ISO 3166-2:IR');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('インド','India','356','IND','IN','南アジア','ISO 3166-2:IN');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('インドネシア','Indonesia','360','IDN','ID','東南アジア','ISO 3166-2:ID');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ウォリス・フツナ','Wallis and Futuna','876','WLF','WF','オセアニア','ISO 3166-2:WF');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ウガンダ','Uganda','800','UGA','UG','中央アフリカ','ISO 3166-2:UG');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ウクライナ','Ukraine','804','UKR','UA','東ヨーロッパ','ISO 3166-2:UA');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ウズベキスタン','Uzbekistan','860','UZB','UZ','中央アジア','ISO 3166-2:UZ');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ウルグアイ','Uruguay','858','URY','UY','南アメリカ','ISO 3166-2:UY');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('エクアドル','Ecuador','218','ECU','EC','南アメリカ','ISO 3166-2:EC');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('エジプト','Egypt','818','EGY','EG','北アフリカ','ISO 3166-2:EG');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('エストニア','Estonia','233','EST','EE','東ヨーロッパ','ISO 3166-2:EE');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('エチオピア','Ethiopia','231','ETH','ET','東アフリカ','ISO 3166-2:ET');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('エリトリア','Eritrea','232','ERI','ER','東アフリカ','ISO 3166-2:ER');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('エルサルバドル','El Salvador','222','SLV','SV','中央アメリカ','ISO 3166-2:SV');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('オーストラリア','Australia','036','AUS','AU','オセアニア','ISO 3166-2:AU');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('オーストリア','Austria','040','AUT','AT','東ヨーロッパ','ISO 3166-2:AT');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('オーランド諸島','Åland Islands','248','ALA','AX','北ヨーロッパ','ISO 3166-2:AX');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('オマーン','Oman','512','OMN','OM','中東','ISO 3166-2:OM');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('オランダ','Netherlands','528','NLD','NL','西ヨーロッパ','ISO 3166-2:NL');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ガーナ','Ghana','288','GHA','GH','西アフリカ','ISO 3166-2:GH');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('カーボベルデ','Cape Verde','132','CPV','CV','西アフリカ','ISO 3166-2:CV');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ガーンジー','Guernsey','831','GGY','GG','西ヨーロッパ','ISO 3166-2:GG');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ガイアナ','Guyana','328','GUY','GY','南アメリカ','ISO 3166-2:GY');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('カザフスタン','Kazakhstan','398','KAZ','KZ','中央アジア','ISO 3166-2:KZ');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('カタール','Qatar','634','QAT','QA','中東','ISO 3166-2:QA');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('合衆国領有小離島','United States Minor Outlying Islands','581','UMI','UM','オセアニア','ISO 3166-2:UM');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('カナダ','Canada','124','CAN','CA','北アメリカ','ISO 3166-2:CA');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ガボン','Gabon','266','GAB','GA','中央アフリカ','ISO 3166-2:GA');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('カメルーン','Cameroon','120','CMR','CM','中央アフリカ','ISO 3166-2:CM');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ガンビア','Gambia','270','GMB','GM','西アフリカ','ISO 3166-2:GM');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('カンボジア','Cambodia','116','KHM','KH','東南アジア','ISO 3166-2:KH');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('北マリアナ諸島','Northern Mariana Islands','580','MNP','MP','オセアニア','ISO 3166-2:MP');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ギニア','Guinea','324','GIN','GN','西アフリカ','ISO 3166-2:GN');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ギニアビサウ','Guinea-Bissau','624','GNB','GW','西アフリカ','ISO 3166-2:GW');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('キプロス','Cyprus','196','CYP','CY','地中海地域','ISO 3166-2:CY');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('キューバ','Cuba','192','CUB','CU','中央アメリカ','ISO 3166-2:CU');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('キュラソー','Curaçao','531','CUW','CW','中央アメリカ','ISO 3166-2:CW');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ギリシャ','Greece','300','GRC','GR','西ヨーロッパ','ISO 3166-2:GR');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('キリバス','Kiribati','296','KIR','KI','オセアニア','ISO 3166-2:KI');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('キルギス','Kyrgyzstan','417','KGZ','KG','中央アジア','ISO 3166-2:KG');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('グアテマラ','Guatemala','320','GTM','GT','中央アメリカ','ISO 3166-2:GT');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('グアドループ','Guadeloupe','312','GLP','GP','中央アメリカ','ISO 3166-2:GP');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('グアム','Guam','316','GUM','GU','オセアニア','ISO 3166-2:GU');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('クウェート','Kuwait','414','KWT','KW','中東','ISO 3166-2:KW');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('クック諸島','Cook Islands','184','COK','CK','オセアニア','ISO 3166-2:CK');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('グリーンランド','Greenland','304','GRL','GL','北ヨーロッパ','ISO 3166-2:GL');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('クリスマス島','Christmas Island','162','CXR','CX','オセアニア','ISO 3166-2:CX');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('グレナダ','Grenada','308','GRD','GD','中央アメリカ','ISO 3166-2:GD');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('クロアチア','Croatia','191','HRV','HR','東ヨーロッパ','ISO 3166-2:HR');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ケイマン諸島','Cayman Islands','136','CYM','KY','中央アメリカ','ISO 3166-2:KY');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ケニア','Kenya','404','KEN','KE','東アフリカ','ISO 3166-2:KE');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('コートジボワール','Côte dIvoire','384','CIV','CI','西アフリカ','ISO 3166-2:CI');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ココス（キーリング）諸島','Cocos (Keeling) Islands','166','CCK','CC','インド洋地域','ISO 3166-2:CC');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('コスタリカ','Costa Rica','188','CRI','CR','中央アメリカ','ISO 3166-2:CR');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('コモロ','Comoros','174','COM','KM','インド洋地域','ISO 3166-2:KM');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('コロンビア','Colombia','170','COL','CO','南アメリカ','ISO 3166-2:CO');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('コンゴ共和国','Congo','178','COG','CG','中央アフリカ','ISO 3166-2:CG');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('コンゴ民主共和国','Congo the Democratic Republic of the','180','COD','CD','中央アフリカ','ISO 3166-2:CD');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('サウジアラビア','Saudi Arabia','682','SAU','SA','中東','ISO 3166-2:SA');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('サウスジョージア・サウスサンドウィッチ諸島','South Georgia and the South Sandwich Islands','239','SGS','GS','南アメリカ','ISO 3166-2:GS');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('サモア','Samoa','882','WSM','WS','オセアニア','ISO 3166-2:WS');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('サントメ・プリンシペ','Sao Tome and Principe','678','STP','ST','中央アフリカ','ISO 3166-2:ST');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('サン・バルテルミー','Saint Barthélemy','652','BLM','BL','中央アメリカ','ISO 3166-2:BL');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ザンビア','Zambia','894','ZMB','ZM','南アフリカ','ISO 3166-2:ZM');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('サンピエール島・ミクロン島','Saint Pierre and Miquelon','666','SPM','PM','北アメリカ','ISO 3166-2:PM');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('サンマリノ','San Marino','674','SMR','SM','西ヨーロッパ','ISO 3166-2:SM');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('サン・マルタン（フランス領）','Saint Martin (French part)','663','MAF','MF','中央アメリカ','ISO 3166-2:MF');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('シエラレオネ','Sierra Leone','694','SLE','SL','西アフリカ','ISO 3166-2:SL');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ジブチ','Djibouti','262','DJI','DJ','東アフリカ','ISO 3166-2:DJ');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ジブラルタル','Gibraltar','292','GIB','GI','西ヨーロッパ','ISO 3166-2:GI');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ジャージー','Jersey','832','JEY','JE','西ヨーロッパ','ISO 3166-2:JE');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ジャマイカ','Jamaica','388','JAM','JM','中央アメリカ','ISO 3166-2:JM');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ジョージア','Georgia','268','GEO','GE','東ヨーロッパ','ISO 3166-2:GE');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('シリア・アラブ共和国','Syrian Arab Republic','760','SYR','SY','中東','ISO 3166-2:SY');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('シンガポール','Singapore','702','SGP','SG','東南アジア','ISO 3166-2:SG');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('シント・マールテン（オランダ領）','Sint Maarten (Dutch part)','534','SXM','SX','中央アメリカ','ISO 3166-2:SX');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ジンバブエ','Zimbabwe','716','ZWE','ZW','南アフリカ','ISO 3166-2:ZW');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('スイス','Switzerland','756','CHE','CH','西ヨーロッパ','ISO 3166-2:CH');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('スウェーデン','Sweden','752','SWE','SE','北ヨーロッパ','ISO 3166-2:SE');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('スーダン','Sudan','729','SDN','SD','東アフリカ','ISO 3166-2:SD');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('スヴァールバル諸島およびヤンマイエン島','Svalbard and Jan Mayen','744','SJM','SJ','北ヨーロッパ','ISO 3166-2:SJ');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('スペイン','Spain','724','ESP','ES','西ヨーロッパ','ISO 3166-2:ES');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('スリナム','Suriname','740','SUR','SR','南アメリカ','ISO 3166-2:SR');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('スリランカ','Sri Lanka','144','LKA','LK','南アジア','ISO 3166-2:LK');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('スロバキア','Slovakia','703','SVK','SK','東ヨーロッパ','ISO 3166-2:SK');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('スロベニア','Slovenia','705','SVN','SI','東ヨーロッパ','ISO 3166-2:SI');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('スワジランド','Swaziland','748','SWZ','SZ','南アフリカ','ISO 3166-2:SZ');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('セーシェル','Seychelles','690','SYC','SC','インド洋地域','ISO 3166-2:SC');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('赤道ギニア','Equatorial Guinea','226','GNQ','GQ','中央アフリカ','ISO 3166-2:GQ');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('セネガル','Senegal','686','SEN','SN','西アフリカ','ISO 3166-2:SN');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('セルビア','Serbia','688','SRB','RS','東ヨーロッパ','ISO 3166-2:RS');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('セントクリストファー・ネイビス','Saint Kitts and Nevis','659','KNA','KN','中央アメリカ','ISO 3166-2:KN');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('セントビンセントおよびグレナディーン諸島','Saint Vincent and the Grenadines','670','VCT','VC','中央アメリカ','ISO 3166-2:VC');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('セントヘレナ・アセンションおよびトリスタンダクーニャ','Saint Helena Ascension and Tristan da Cunha','654','SHN','SH','西アフリカ','ISO 3166-2:SH');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('セントルシア','Saint Lucia','662','LCA','LC','中央アメリカ','ISO 3166-2:LC');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ソマリア','Somalia','706','SOM','SO','東アフリカ','ISO 3166-2:SO');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ソロモン諸島','Solomon Islands','090','SLB','SB','オセアニア','ISO 3166-2:SB');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('タークス・カイコス諸島','Turks and Caicos Islands','796','TCA','TC','中央アメリカ','ISO 3166-2:TC');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('タイ','Thailand','764','THA','TH','東南アジア','ISO 3166-2:TH');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('大韓民国','Korea Republic of','410','KOR','KR','東アジア','ISO 3166-2:KR');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('台湾','Taiwan Province of China','158','TWN','TW','東アジア','ISO 3166-2:TW');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('タジキスタン','Tajikistan','762','TJK','TJ','中央アジア','ISO 3166-2:TJ');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('タンザニア','Tanzania United Republic of','834','TZA','TZ','東アフリカ','ISO 3166-2:TZ');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('チェコ','Czechia','203','CZE','CZ','東ヨーロッパ','ISO 3166-2:CZ');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('チャド','Chad','148','TCD','TD','中央アフリカ','ISO 3166-2:TD');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('中央アフリカ共和国','Central African Republic','140','CAF','CF','中央アフリカ','ISO 3166-2:CF');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('中華人民共和国','China','156','CHN','CN','東アジア','ISO 3166-2:CN');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('チュニジア','Tunisia','788','TUN','TN','北アフリカ','ISO 3166-2:TN');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('朝鮮民主主義人民共和国','Korea Democratic Peoples Republic of','408','PRK','KP','東アジア','ISO 3166-2:KP');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('チリ','Chile','152','CHL','CL','南アメリカ','ISO 3166-2:CL');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ツバル','Tuvalu','798','TUV','TV','オセアニア','ISO 3166-2:TV');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('デンマーク','Denmark','208','DNK','DK','北ヨーロッパ','ISO 3166-2:DK');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ドイツ','Germany','276','DEU','DE','西ヨーロッパ','ISO 3166-2:DE');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('トーゴ','Togo','768','TGO','TG','西アフリカ','ISO 3166-2:TG');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('トケラウ','Tokelau','772','TKL','TK','オセアニア','ISO 3166-2:TK');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ドミニカ共和国','Dominican Republic','214','DOM','DO','中央アメリカ','ISO 3166-2:DO');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ドミニカ国','Dominica','212','DMA','DM','中央アメリカ','ISO 3166-2:DM');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('トリニダード・トバゴ','Trinidad and Tobago','780','TTO','TT','中央アメリカ','ISO 3166-2:TT');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('トルクメニスタン','Turkmenistan','795','TKM','TM','中央アジア','ISO 3166-2:TM');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('トルコ','Turkey','792','TUR','TR','中東','ISO 3166-2:TR');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('トンガ','Tonga','776','TON','TO','オセアニア','ISO 3166-2:TO');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ナイジェリア','Nigeria','566','NGA','NG','中央アフリカ','ISO 3166-2:NG');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ナウル','Nauru','520','NRU','NR','オセアニア','ISO 3166-2:NR');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ナミビア','Namibia','516','NAM','NA','南アフリカ','ISO 3166-2:NA');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('南極','Antarctica','010','ATA','AQ','南極','ISO 3166-2:AQ');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ニウエ','Niue','570','NIU','NU','オセアニア','ISO 3166-2:NU');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ニカラグア','Nicaragua','558','NIC','NI','中央アメリカ','ISO 3166-2:NI');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ニジェール','Niger','562','NER','NE','中央アフリカ','ISO 3166-2:NE');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('日本','Japan','392','JPN','JP','東アジア','ISO 3166-2:JP');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('西サハラ','Western Sahara','732','ESH','EH','西アフリカ','ISO 3166-2:EH');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ニューカレドニア','New Caledonia','540','NCL','NC','オセアニア','ISO 3166-2:NC');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ニュージーランド','New Zealand','554','NZL','NZ','オセアニア','ISO 3166-2:NZ');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ネパール','Nepal','524','NPL','NP','南アジア','ISO 3166-2:NP');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ノーフォーク島','Norfolk Island','574','NFK','NF','オセアニア','ISO 3166-2:NF');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ノルウェー','Norway','578','NOR','NO','北ヨーロッパ','ISO 3166-2:NO');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ハード島とマクドナルド諸島','Heard Island and McDonald Islands','334','HMD','HM','インド洋地域','ISO 3166-2:HM');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('バーレーン','Bahrain','048','BHR','BH','中東','ISO 3166-2:BH');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ハイチ','Haiti','332','HTI','HT','中央アメリカ','ISO 3166-2:HT');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('パキスタン','Pakistan','586','PAK','PK','南アジア','ISO 3166-2:PK');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('バチカン市国','Holy See (Vatican City State)','336','VAT','VA','西ヨーロッパ','ISO 3166-2:VA');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('パナマ','Panama','591','PAN','PA','中央アメリカ','ISO 3166-2:PA');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('バヌアツ','Vanuatu','548','VUT','VU','オセアニア','ISO 3166-2:VU');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('バハマ','Bahamas','044','BHS','BS','中央アメリカ','ISO 3166-2:BS');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('パプアニューギニア','Papua New Guinea','598','PNG','PG','オセアニア','ISO 3166-2:PG');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('バミューダ','Bermuda','060','BMU','BM','中央アメリカ','ISO 3166-2:BM');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('パラオ','Palau','585','PLW','PW','オセアニア','ISO 3166-2:PW');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('パラグアイ','Paraguay','600','PRY','PY','南アメリカ','ISO 3166-2:PY');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('バルバドス','Barbados','052','BRB','BB','中央アメリカ','ISO 3166-2:BB');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('パレスチナ','Palestinian Territory Occupied','275','PSE','PS','中東','ISO 3166-2:PS');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ハンガリー','Hungary','348','HUN','HU','東ヨーロッパ','ISO 3166-2:HU');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('バングラデシュ','Bangladesh','050','BGD','BD','南アジア','ISO 3166-2:BD');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('東ティモール','Timor-Leste','626','TLS','TL','東南アジア','ISO 3166-2:TL');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ピトケアン','Pitcairn','612','PCN','PN','オセアニア','ISO 3166-2:PN');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('フィジー','Fiji','242','FJI','FJ','オセアニア','ISO 3166-2:FJ');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('フィリピン','Philippines','608','PHL','PH','東南アジア','ISO 3166-2:PH');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('フィンランド','Finland','246','FIN','FI','北ヨーロッパ','ISO 3166-2:FI');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ブータン','Bhutan','064','BTN','BT','南アジア','ISO 3166-2:BT');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ブーベ島','Bouvet Island','074','BVT','BV','南極','ISO 3166-2:BV');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('プエルトリコ','Puerto Rico','630','PRI','PR','中央アメリカ','ISO 3166-2:PR');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('フェロー諸島','Faroe Islands','234','FRO','FO','北ヨーロッパ','ISO 3166-2:FO');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('フォークランド（マルビナス）諸島','Falkland Islands (Malvinas)','238','FLK','FK','南アメリカ','ISO 3166-2:FK');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ブラジル','Brazil','076','BRA','BR','南アメリカ','ISO 3166-2:BR');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('フランス','France','250','FRA','FR','西ヨーロッパ','ISO 3166-2:FR');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('フランス領ギアナ','French Guiana','254','GUF','GF','南アメリカ','ISO 3166-2:GF');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('フランス領ポリネシア','French Polynesia','258','PYF','PF','オセアニア','ISO 3166-2:PF');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('Flag of the French Southern and Antarctic Lands.svg フランス領南方・南極地域','French Southern Territories','260','ATF','TF','インド洋地域','ISO 3166-2:TF');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ブルガリア','Bulgaria','100','BGR','BG','東ヨーロッパ','ISO 3166-2:BG');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ブルキナファソ','Burkina Faso','854','BFA','BF','西アフリカ','ISO 3166-2:BF');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ブルネイ・ダルサラーム','Brunei Darussalam','096','BRN','BN','東南アジア','ISO 3166-2:BN');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ブルンジ','Burundi','108','BDI','BI','中央アフリカ','ISO 3166-2:BI');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ベトナム','Viet Nam','704','VNM','VN','東南アジア','ISO 3166-2:VN');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ベナン','Benin','204','BEN','BJ','西アフリカ','ISO 3166-2:BJ');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ベネズエラ・ボリバル共和国','Venezuela Bolivarian Republic of','862','VEN','VE','南アメリカ','ISO 3166-2:VE');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ベラルーシ','Belarus','112','BLR','BY','東ヨーロッパ','ISO 3166-2:BY');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ベリーズ','Belize','084','BLZ','BZ','中央アメリカ','ISO 3166-2:BZ');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ペルー','Peru','604','PER','PE','南アメリカ','ISO 3166-2:PE');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ベルギー','Belgium','056','BEL','BE','西ヨーロッパ','ISO 3166-2:BE');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ポーランド','Poland','616','POL','PL','東ヨーロッパ','ISO 3166-2:PL');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ボスニア・ヘルツェゴビナ','Bosnia and Herzegovina','070','BIH','BA','東ヨーロッパ','ISO 3166-2:BA');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ボツワナ','Botswana','072','BWA','BW','南アフリカ','ISO 3166-2:BW');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ボネール、シント・ユースタティウスおよびサバ','Bonaire Saint Eustatius and Saba','535','BES','BQ','中央アメリカ','ISO 3166-2:BQ');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ボリビア多民族国','Bolivia Plurinational State of','068','BOL','BO','南アメリカ','ISO 3166-2:BO');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ポルトガル','Portugal','620','PRT','PT','西ヨーロッパ','ISO 3166-2:PT');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('香港','Hong Kong','344','HKG','HK','東アジア','ISO 3166-2:HK');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ホンジュラス','Honduras','340','HND','HN','中央アメリカ','ISO 3166-2:HN');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('マーシャル諸島','Marshall Islands','584','MHL','MH','オセアニア','ISO 3166-2:MH');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('マカオ','Macau','446','MAC','MO','東アジア','ISO 3166-2:MO');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('マケドニア旧ユーゴスラビア共和国','Macedonia the former Yugoslav Republic of','807','MKD','MK','東ヨーロッパ','ISO 3166-2:MK');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('マダガスカル','Madagascar','450','MDG','MG','インド洋地域','ISO 3166-2:MG');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('マヨット','Mayotte','175','MYT','YT','インド洋地域','ISO 3166-2:YT');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('マラウイ','Malawi','454','MWI','MW','南アフリカ','ISO 3166-2:MW');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('マリ','Mali','466','MLI','ML','西アフリカ','ISO 3166-2:ML');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('マルタ','Malta','470','MLT','MT','地中海地域','ISO 3166-2:MT');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('マルティニーク','Martinique','474','MTQ','MQ','中央アメリカ','ISO 3166-2:MQ');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('マレーシア','Malaysia','458','MYS','MY','東南アジア','ISO 3166-2:MY');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('マン島','Isle of Man','833','IMN','IM','西ヨーロッパ','ISO 3166-2:IM');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ミクロネシア連邦','Micronesia Federated States of','583','FSM','FM','オセアニア','ISO 3166-2:FM');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('南アフリカ','South Africa','710','ZAF','ZA','南アフリカ','ISO 3166-2:ZA');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('南スーダン','South Sudan','728','SSD','SS','東アフリカ','ISO 3166-2:SS');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ミャンマー','Myanmar','104','MMR','MM','東南アジア','ISO 3166-2:MM');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('メキシコ','Mexico','484','MEX','MX','中央アメリカ','ISO 3166-2:MX');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('モーリシャス','Mauritius','480','MUS','MU','南アフリカ','ISO 3166-2:MU');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('モーリタニア','Mauritania','478','MRT','MR','西アフリカ','ISO 3166-2:MR');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('モザンビーク','Mozambique','508','MOZ','MZ','南アフリカ','ISO 3166-2:MZ');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('モナコ','Monaco','492','MCO','MC','西ヨーロッパ','ISO 3166-2:MC');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('モルディブ','Maldives','462','MDV','MV','インド洋地域','ISO 3166-2:MV');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('モルドバ共和国','Moldova Republic of','498','MDA','MD','東ヨーロッパ','ISO 3166-2:MD');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('モロッコ','Morocco','504','MAR','MA','北アフリカ','ISO 3166-2:MA');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('モンゴル','Mongolia','496','MNG','MN','東アジア','ISO 3166-2:MN');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('モンテネグロ','Montenegro','499','MNE','ME','東ヨーロッパ','ISO 3166-2:ME');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('モントセラト','Montserrat','500','MSR','MS','中央アメリカ','ISO 3166-2:MS');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ヨルダン','Jordan','400','JOR','JO','中東','ISO 3166-2:JO');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ラオス人民民主共和国','Lao Peoples Democratic Republic','418','LAO','LA','東南アジア','ISO 3166-2:LA');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ラトビア','Latvia','428','LVA','LV','東ヨーロッパ','ISO 3166-2:LV');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('リトアニア','Lithuania','440','LTU','LT','東ヨーロッパ','ISO 3166-2:LT');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('リビア','Libya','434','LBY','LY','北アフリカ','ISO 3166-2:LY');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('リヒテンシュタイン','Liechtenstein','438','LIE','LI','西ヨーロッパ','ISO 3166-2:LI');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('リベリア','Liberia','430','LBR','LR','西アフリカ','ISO 3166-2:LR');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ルーマニア','Romania','642','ROU','RO','東ヨーロッパ','ISO 3166-2:RO');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ルクセンブルク','Luxembourg','442','LUX','LU','西ヨーロッパ','ISO 3166-2:LU');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ルワンダ','Rwanda','646','RWA','RW','中央アフリカ','ISO 3166-2:RW');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('レソト','Lesotho','426','LSO','LS','南アフリカ','ISO 3166-2:LS');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('レバノン','Lebanon','422','LBN','LB','中東','ISO 3166-2:LB');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('レユニオン','Réunion','638','REU','RE','インド洋地域','ISO 3166-2:RE');
insert into m_country(name_jp,name_eng,code,alpha_3,alpha_2,region,iso_3166_2)values('ロシア連邦','Russian Federation','643','RUS','RU','ロシア','ISO 3166-2:RU');
